version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/wordpress
    restart: always
    networks:
      - localhost

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DATABASE: $MYSQL_DATABASE
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
        HOSTNAME: $MYSQL_HOSTNAME
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/wordpress
    restart: always
    networks:
      - localhost

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DATABASE: $MYSQL_DATABASE
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
    container_name: mariadb
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - localhost

networks:
  localhost:
    name: gplaid.42.fr
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gplaid/data/wordpress
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gplaid/data/mysql
