version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DATABASE: $MYSQL_DATABASE
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
        HOSTNAME: $MYSQL_HOSTNAME
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DATABASE: $MYSQL_DATABASE
        USER: $MYSQL_USER
        PASSWORD: $MYSQL_PASSWORD
    build: ./requirements/mariadb
    container_name: mariadb

volumes:
  wordpress:
